### ISSUE TITLE
Delete siri shortcut right after add it through AddSiriButton cause presentShortcut modal can't show properly 

### ISSUE THREAD

**Issue by BrianCodeItUp** [Gustash/react-native-siri-shortcut#44]
## Description
Delete siri shortcut right after add it through AddSiriButton cause presentShortcut modal can't show properly

## Version
React Native: 0.59.10
react-native-siri-shortcut: 1.6.4
ios: 13.1 or above (as far as i tested on real devices)

## Steps To Reproduce
1. Using AddSiriButton to emit onPress to tigger presentShortcut method
2. Swipe App to background 
3. Delete the shortcut just created
4. Back to App and press AddSiriButton to tigger presentShortcut method again

## Error Behavior And Expected Result
- Error Behavior
![Siri Shortcut error](https://user-images.githubusercontent.com/34977345/81783480-f681f380-952d-11ea-86c0-85c3a384355a.gif)
- Expected Behavior
![sirir Shortcut expected behavior](https://user-images.githubusercontent.com/34977345/81783566-203b1a80-952e-11ea-95b8-ec153087020b.gif)

**Comment by Gustash** [comment]
From the video it seems like you're using a Modal. On iOS, Modals usually interfere with other View Controllers trying to be shown. If you are using one, can you try moving the button outside of it and checking if the same happens?

**Comment by BrianCodeItUp** [comment]
@Gustash  I tried to move AddSiriButton out as as a  common button but it results the same situation. I suspected it has something to do with deleting the shortcut but App is still running and does't know which shortcut to edit since the shortcut has been deleted.
Here the way i test it: 
![remove addsirbtn  out of modal test](https://user-images.githubusercontent.com/34977345/81790185-9e4fef00-9537-11ea-8088-785177d1e873.gif)

**Comment by Gustash** [comment]
I was able to replicate the issue you're describing. I will try to take a look today, sorry for the confusion

**Comment by Gustash** [comment]
@BrianCodeItUp just released v1.8.0, should fix this problem.

The issue was that the internal array keeping track of the added voice shortcuts was only being updated when CRUD operations were performed internally, so it wouldn't know about changes on the Shortcuts app.

On v1.8.0, the package is overriding that state with whatever the OS has currently whenever the app comes back into the foreground. I wasn't able to replicate this issue anymore after this fix.

Let me know if this is fixed for you so I can close this issue, please.

**Comment by BrianCodeItUp** [comment]
@Gustash After upgrading to v18.0,  this issue has been resolved. Thank you for the quick update to fix this issue.
