### ISSUE TITLE
Activate Siri target instead of opening app from shortcut

### ISSUE THREAD

**Issue by anekadmin** [Gustash/react-native-siri-shortcut#50]
Any guidance on using this library to handle intents with conversational siri interface? I tried and the shortcut keeps opening the app instead of running the siri target.

**Comment by Gustash** [comment]
Refer to #43. In short, it's impossible to support Intent Extensions in the background because the JS bridge can't run on them. I've pinned this issue since it's a recurring question people have.

As a side note, iOS 14 introduces in-app siri intents, and I want to integrate them into the package, but that requires React Native to move to UIScene instead of UIApplication internally.

You can track that issue [here](https://github.com/facebook/react-native/issues/25181#issuecomment-502081954). If that ever gets resolved I will try to at least add in-app intent support.
